---
title: 'SDS 237: Final Project Checkpoint 7 - Institutional Incentives'
author:
  - Fill
  - Fill
  - Fill
  - Fill
date: 09/30/2021
output: 
  rmdformats::readthedown:
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

## Part 1: Stakeholder Mapping

> Note that this part is to set up your thinking and analysis, and will likely not appear in the final user guide.

Last week, you characterized at least two social groups implicated in your dataset. For each of these social groups, complete the claim below. This is going to feel reductionist, and it is, but go with it for now. 

1. ______ has [high/low] influence over the data, and [high/low] interest in the data. 
2. ______ has [high/low] influence over the data, and [high/low] interest in the data.


Refer back to the causal argument frames we discussed on Tuesday. Select one frame, and use it to detail the *reasons* why this stakeholder has this degree influence over or interest in the data. Feel free to bullet this section, but I encourage you to think carefully and critically here, offering more than single word bullets. 

Stakeholder 1:

* 
* 
* 
* 
* 

Stakeholder 2:

* 
* 
* 
* 
* 

## Part 2: Identify institutions

After reviewing your causal arguments, identify at least four institutions that have some degree of influence over the things that people say or do in relation to the data, in other words, their interest or their influence. At least one stakeholder should be the agency that oversees the data collection, or a specific office within that agency. List those institutions below, and for each describe their role in the production or stewardship of the data in about 100 words. You might consider the ways in which this institution incentivizes people involved in data production to collect the data in specific ways, the protocols they enforce regarding data collection, etc. This text *will* appear in the final user guide, so to reduce the need for revision later, you may consider how to write this section with the user guide's audience in mind. 

1. 
2. 
3. 
4. 

## Part 3: Network Mapping

Install the igraph package in your console with the following code:

install.packages("igraph")

Open the graph_links.csv file in Excel. *Each row of this dataset should indicate one relationship amongst stakeholders or institutions implicated in your data, and the value of the importance column should indicate the strength of that relationship (on a scale of 1-3).* Replace the letters in this file with stakeholders and institutions. Be sure to use common spelling for repeating stakeholders or institutions. Save the file.

Open the graph_nodes.csv file in Excel. Each row should list one stakeholder or institution listed in graph_links.csv (use the same exact spelling), and whether that row indicates a stakeholder or institution. Save the file.

Run the code below to visualize the relationships. If you'd like the customize this plot further, see https://www.r-graph-gallery.com/network.html


```{r}
library(igraph)

links <- read.csv("graph_datasets/graph_links.csv")
nodes <- read.csv("graph_datasets/graph_nodes.csv")

# Turn it into igraph object
network <- graph_from_data_frame(d = links, 
                                 vertices = nodes, 
                                 directed = F) 
 
# Make a palette of 2 colors
library(RColorBrewer)
pal <- brewer.pal(3, "Set2") 
 
# Create a vector of color
my_pal <- pal[as.numeric(as.factor(V(network)$type))]
 
# Make the plot
plot(network, 
     vertex.color = my_pal,
     vertex.size = 30,
     vertex.label.family = "Arial",
     vertex.label.cex = 0.5,
     vertex.label.color = "black",
     edge.width = E(network)$importance * 2)
 
# Add a legend
legend("bottomleft", 
       legend = levels(as.factor(V(network)$type)), 
       col = pal, 
       pch = 20 , 
       text.col = pal, 
       horiz = FALSE)
```

Explain what this plot shows to the user in about 100 words. This graph and text *will* appear in the final user guide. 




